# Generated by Django 5.0.6 on 2024-06-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=255)),
                ('organizer', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
